// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxN11TxuESynU8_k3Jz8J1nypbi93EkGY',
    appId: '1:750572798291:web:d81c9c162ce18044b4a1a6',
    messagingSenderId: '750572798291',
    projectId: 'picture-perfect-app-e9002',
    authDomain: 'picture-perfect-app-e9002.firebaseapp.com',
    storageBucket: 'picture-perfect-app-e9002.firebasestorage.app',
    measurementId: 'G-7J92YV9RJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrxqFf6uNoY1BCUMlQWIPdRsdAWZzufbo',
    appId: '1:750572798291:android:b2e0a54f3bb88069b4a1a6',
    messagingSenderId: '750572798291',
    projectId: 'picture-perfect-app-e9002',
    storageBucket: 'picture-perfect-app-e9002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEH5r5QJk8Sm6TJNV56TJC9ZlkFdtjTg',
    appId: '1:750572798291:ios:e0931aafe38b8881b4a1a6',
    messagingSenderId: '750572798291',
    projectId: 'picture-perfect-app-e9002',
    storageBucket: 'picture-perfect-app-e9002.firebasestorage.app',
    iosBundleId: 'com.example.picturePerfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEH5r5QJk8Sm6TJNV56TJC9ZlkFdtjTg',
    appId: '1:750572798291:ios:e0931aafe38b8881b4a1a6',
    messagingSenderId: '750572798291',
    projectId: 'picture-perfect-app-e9002',
    storageBucket: 'picture-perfect-app-e9002.firebasestorage.app',
    iosBundleId: 'com.example.picturePerfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxN11TxuESynU8_k3Jz8J1nypbi93EkGY',
    appId: '1:750572798291:web:e5e48bdd2f7d7fdcb4a1a6',
    messagingSenderId: '750572798291',
    projectId: 'picture-perfect-app-e9002',
    authDomain: 'picture-perfect-app-e9002.firebaseapp.com',
    storageBucket: 'picture-perfect-app-e9002.firebasestorage.app',
    measurementId: 'G-XXS5W6HMK0',
  );

}